GET https://donnermayer-AzureDemos.Function.azurewebsites.net/api/AzureDemos.Function

{
    "name" : "Elisaa",
    "x" : "1.0",
    "y" : "2.0"
}
###

GET http://localhost:7072/api/AzureDemos.Function?name=Jan  