GET https://donnermayer-azurefunctionsdemo.azurewebsites.net/api/AzureFunctionsDemo

{
    "name" : "Elisaa",
    "x" : 1,
    "y" : 2
}
###

GET http://localhost:7072/api/AzureFunctionsDemo?name=Jan  