GET https://donnermayer-Demos.AzureFunction.azurewebsites.net/api/Demos.AzureFunction

{
    "name" : "Elisaa",
    "x" : "1.0",
    "y" : "2.0"
}
###

GET http://localhost:7072/api/Demos.AzureFunction?name=Jan  